### ISSUE TITLE
Insertion point needs tweaking

### ISSUE THREAD

**Issue by ashfame** [molbal/ai-phpdoc#4]
Currently generated phpdocs are inserted with no new line before it and an extra line after it. Example:

```
	}
	/**
	* Handles authentication requests
	 *
	 * @param Request $request The request object
	 * @param Response $response The response object
	*/

	public function authenticate_handler() {

```

Also you can see first text line and last line needs an extra space in indentation.

**Comment by molbal** [comment]
Yes I've noticed it as well - feel free to submit a PR, I won't get around to fixing it for weeks

**Comment by molbal** [comment]
npotier fixed it
